// DEPENDENCIES:
// --------------------------------------------------------------

  // External to the application
  require('dotenv').config();
  const express = require("express");
  const mongoose = require("mongoose");
  const app = express();
  const PORT = process.env.PORT || 3001;
  const path = require("path");
  const bodyParser = require("body-parser");

  // Internal to the application
  const routes = require("./routes");
 

// CONNECTIONS AND DEFINITIONS
// --------------------------------------------------------------

  // Middleware definition
  app.use(express.urlencoded({ extended: true }));
  app.use(express.json());

  // gives server access to static files generated by running node build in client
  app.use(express.static(path.join(__dirname, './client/build')));

  // Add routes, both API and view
  app.use(routes);

  require("./dal/connection").connect();

  // send all requests to react
  app.get("/*", (req, res) => {
    res.sendFile("index.html", { root: __dirname + "/client/build"});
  });

  // Start the API server
  app.listen(PORT, function() {
    console.log(`🌎  ==> API Server now listening on PORT ${PORT}!`);
  });
